<?php

namespace AppBundle\Repository;

/**
 * PlayerLvlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerLvlRepository extends \Doctrine\ORM\EntityRepository
{
}
