<?php

namespace AppBundle\Repository;

/**
 * PlayerGuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerGuildRepository extends \Doctrine\ORM\EntityRepository
{
}
