<?php

namespace App\Repository;

/**
 * GuildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuildRepository extends \Doctrine\ORM\EntityRepository
{
}
