<?php

namespace App\Repository;

/**
 * PlayerChampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerChampRepository extends \Doctrine\ORM\EntityRepository
{
}
