<?php

namespace App\Repository;

/**
 * PlayerNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerNameRepository extends \Doctrine\ORM\EntityRepository
{
}
