<?php

namespace App\Repository;

/**
 * PlayerUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerUserRepository extends \Doctrine\ORM\EntityRepository
{
}
